//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.SeeCount = 0;
            this.SaleInfo = new HashSet<SaleInfo>();
            this.Shoping = new HashSet<Shoping>();
            this.MySee = new HashSet<MySee>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public short Type { get; set; }
        public string MaiDian { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
        public string LaiYuan { get; set; }
        public string BigImageAddress { get; set; }
        public string Descript { get; set; }
        public short DelGlag { get; set; }
        public System.DateTime SubTime { get; set; }
        public int UserInfoId { get; set; }
        public string SmallImageAddress { get; set; }
        public int ShopingId { get; set; }
        public int SeeCount { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<SaleInfo> SaleInfo { get; set; }
        public virtual ICollection<Shoping> Shoping { get; set; }
        public virtual ICollection<MySee> MySee { get; set; }
    }
}
