//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListShops
    {
        public ListShops()
        {
            this.IsShenHe = 0;
        }
    
        public int Id { get; set; }
        public System.DateTime SubTime { get; set; }
        public int UserInfoId { get; set; }
        public short Status { get; set; }
        public string RealName { get; set; }
        public string IdCard { get; set; }
        public string CardAddress { get; set; }
        public string CalssName { get; set; }
        public short IsShenHe { get; set; }
        public Nullable<int> SheHeAdminId { get; set; }
    }
}
