//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qtcSecondHandEntities : DbContext
    {
        public qtcSecondHandEntities()
            : base("name=qtcSecondHandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Goods> Goods { get; set; }
        public DbSet<SaleInfo> SaleInfo { get; set; }
        public DbSet<Shoping> Shoping { get; set; }
        public DbSet<UserInfoExt> UserInfoExt { get; set; }
        public DbSet<MySee> MySee { get; set; }
        public DbSet<Suggest> Suggest { get; set; }
        public DbSet<ListShops> ListShops { get; set; }
        public DbSet<MyNews> MyNews { get; set; }
        public DbSet<AdminUser> AdminUser { get; set; }
        public DbSet<ShiWu> ShiWu { get; set; }
        public DbSet<FriendLink> FriendLink { get; set; }
    }
}
