//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiWu
    {
        public int Id { get; set; }
        public string PhoneNum { get; set; }
        public string ThingName { get; set; }
        public string Descript { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public short Type { get; set; }
        public System.DateTime Time { get; set; }
    }
}
