//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggest
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public short OpenSpeed { get; set; }
        public short Beautiful { get; set; }
        public short SettingType { get; set; }
        public short Convenient { get; set; }
        public short Vivid { get; set; }
        public short AllPopulation { get; set; }
        public short Aim { get; set; }
        public string QQNum { get; set; }
        public string Email { get; set; }
        public string PhoneNum { get; set; }
        public System.DateTime SubTime { get; set; }
    }
}
