//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Goods = new HashSet<Goods>();
            this.Shoping = new HashSet<Shoping>();
            this.MySee = new HashSet<MySee>();
            this.MyNews = new HashSet<MyNews>();
        }
    
        public int Id { get; set; }
        public string Uid { get; set; }
        public string Pwd { get; set; }
        public short DelFalg { get; set; }
        public string Email { get; set; }
        public short IsValid { get; set; }
        public Nullable<System.DateTime> SendEmailTime { get; set; }
        public System.DateTime SubTime { get; set; }
        public string EmailCode { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual ICollection<Shoping> Shoping { get; set; }
        public virtual ICollection<MySee> MySee { get; set; }
        public virtual ICollection<MyNews> MyNews { get; set; }
    }
}
