//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLXK.SecondHand.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoExt
    {
        public UserInfoExt()
        {
            this.NickName = " ";
        }
    
        public int Id { get; set; }
        public int UserInfoId { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public short Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string TouXiang { get; set; }
    }
}
